[package]
name = "zeronet_wrapper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zeronet_cryptography = "0.1.8"

[lib]
name = "zeronet_wrapper"
crate-type = ["staticlib", "cdylib"]
